create table emp_details(id INT UNSIGNED AUTO_INCREMENT , EMP_ID INT(10) NOT NULL,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(1000) NOT NULL,
  DESIGNATION VARCHAR(100),
  EMAIL VARCHAR(100),
  PHONE VARCHAR(100));